version: 2

key: &src-cache-key src-{{ .Branch }}-{{ .Revision }}
key: &npm-dependencies-cache-key npm-dependencies-{{ checksum "package.json" }}
key: &npm-prod-cache-key prod-{{ .Branch }}-{{ .Revision }}

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:9.2.1
    working_directory: /home/circleci/project
    steps:
      - checkout
      - save_cache:
          paths:
            - ./
          key: *src-cache-key
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
  build_and_deploy_prod:
    docker:
      - image: circleci/node:9.2.1
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: *src-cache-key
      - restore_cache:
          key: *npm-dependencies-cache-key
      - run:
          name: Build package
          command: |
            node ./scripts/prebuild.js
            node ./scripts/version.js
            node ./node_modules/@angular/cli/bin/ng build --env=prod
      - run:
          name: "Publish to Firestore"
          command: |
            ls -la
            node node_modules/firebase-tools/bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
      - save_cache:
          paths:
            - out
          key: *npm-prod-cache-key

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - build_and_deploy_prod:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - develop